name: macsignaturepad
description: MAC Agentur Signature Pad

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.25.5
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.15.6
  firebase_storage: ^11.6.7
  firebase_ui_auth: ^1.13.1
  hand_signature: ^3.0.2
  lottie: ^3.1.0
  country_code_picker: ^3.0.0
  dio: ^5.4.1
  syncfusion_flutter_pdf: ^24.2.8
  syncfusion_flutter_pdfviewer: ^24.2.8
  url_launcher: ^6.2.5
  intl: ^0.18.1

  # flutter_pdfview: ^1.2.7
  # pdfx: ^2.5.0
  # internet_file: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/