name: macsignaturepad
description: MAC Agentur Signature Pad

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  firebase_ui_auth: ^3.0.0
  hand_signature: ^3.1.0+2
  lottie: ^3.3.1
  country_code_picker: ^3.4.0
  url_launcher: ^6.3.2
  file_picker: ^10.3.2
  image_picker: ^1.2.0
  syncfusion_flutter_pdf: ^31.1.17
  syncfusion_flutter_pdfviewer: ^31.1.17
  dio: ^5.9.0
  intl: ^0.20.2

dependency_overrides:
  win32: ^5.14.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/