name: macsignaturepad
description: MAC Agentur Signature Pad

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.0
  firebase_ui_auth: ^1.15.0
  hand_signature: ^3.0.3
  lottie: ^3.1.2
  country_code_picker: ^3.0.0
  dio: ^5.4.3+1
  url_launcher: ^6.3.0
  file_picker: ^8.0.5
  syncfusion_flutter_pdf: ^26.1.39
  syncfusion_flutter_pdfviewer: ^26.1.39
  intl: ^0.19.0

  # flutter_pdfview: ^1.2.7
  # pdfx: ^2.5.0
  # internet_file: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/