name: macsignaturepad
description: MAC Agentur Signature Pad

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4
  firebase_storage: ^12.4.3
  firebase_ui_auth: ^1.16.1
  hand_signature: ^3.0.3
  lottie: ^3.3.1
  country_code_picker: ^3.2.0
  url_launcher: ^6.3.1
  file_picker: ^9.0.1
  syncfusion_flutter_pdf: ^28.2.7
  syncfusion_flutter_pdfviewer: ^28.2.7
  dio: ^5.7.0
  intl: ^0.19.0

dependency_overrides:
  win32: ^5.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/