// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRsIGon3wb_mhk49SBVu_CRfkvFkWxgmQ',
    appId: '1:240478330227:web:c75d1839ade4526a907906',
    messagingSenderId: '240478330227',
    projectId: 'mac-signature-pad',
    authDomain: 'mac-signature-pad.firebaseapp.com',
    storageBucket: 'mac-signature-pad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJXwDutjxZjuftJxKgH5T6MJhfd8MAy6k',
    appId: '1:240478330227:android:2207b41c9d9ca8eb907906',
    messagingSenderId: '240478330227',
    projectId: 'mac-signature-pad',
    storageBucket: 'mac-signature-pad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOSDasmsWi4l1oJfl5gLv6v4iXKM2kcVs',
    appId: '1:240478330227:ios:213acc947d403e5c907906',
    messagingSenderId: '240478330227',
    projectId: 'mac-signature-pad',
    storageBucket: 'mac-signature-pad.appspot.com',
    iosBundleId: 'com.kreiseck.macsignaturepad',
  );
}
